rootProject.name = 'first-logistics'

include 'sample-service'
include 'common'
include 'common-jpa'
include 'common-event'
include 'common-security'
include 'company-service'
include 'notification-service'
include 'order-service'
include 'delivery-service'
include 'eureka-server'
include 'api-gateway'
include 'user-service'
include 'hub-service'
include 'product-service'