spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI:http://keycloak:8080/realms/codefactory}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
      routes:
        - id: user-service  # 라우트 식별자
          uri: lb://user-service # 'users-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/v1/users/** # /users/** 경로로 들어오는 요청을 이 라우트로 처리
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**, /api/v1/delivery-managers/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**, /api/v1/hub-connections/**, /api/v1/hub-managers/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/slack/**, /api/v1/ai-logs/**

        # Swagger api-docs 라우트
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs
        - id: delivery-service-docs
          uri: lb://delivery-service
          predicates:
            - Path=/v3/api-docs/delivery-service
          filters:
            - RewritePath=/v3/api-docs/delivery-service, /v3/api-docs
        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs
        - id: hub-service-docs
          uri: lb://hub-service
          predicates:
            - Path=/v3/api-docs/hub-service
          filters:
            - RewritePath=/v3/api-docs/hub-service, /v3/api-docs
        - id: company-service-docs
          uri: lb://company-service
          predicates:
            - Path=/v3/api-docs/company-service
          filters:
            - RewritePath=/v3/api-docs/company-service, /v3/api-docs
        - id: product-service-docs
          uri: lb://product-service
          predicates:
            - Path=/v3/api-docs/product-service
          filters:
            - RewritePath=/v3/api-docs/product-service, /v3/api-docs
        - id: notification-service-docs
          uri: lb://notification-service
          predicates:
            - Path=/v3/api-docs/notification-service
          filters:
            - RewritePath=/v3/api-docs/notification-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: delivery-service
        url: /v3/api-docs/delivery-service
      - name: order-service
        url: /v3/api-docs/order-service
      - name: hub-service
        url: /v3/api-docs/hub-service
      - name: company-service
        url: /v3/api-docs/company-service
      - name: product-service
        url: /v3/api-docs/product-service
      - name: notification-service
        url: /v3/api-docs/notification-service

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8080/eureka/
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}