server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: redrock1004!

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

keycloak:
  server-url: http://localhost:3300
  realm: codefactory
  client-id: spring-app
  client-secret: Eju0knPo8BsChh39Gn2aNa4Hep01PKux
  admin-username: admin
  admin-password: admin