spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: delivery
  data:
    redis:
      url: ${REDIS_URL}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8080}
hub-service:
  url: ${HUB_SERVICE_URL:http://localhost:8083}
company-service:
  url: ${COMPANY_SERVICE_URL:http://localhost:8084}

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}